name: Java CI with Maven

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Action
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh    
    - name: Build with Maven
      run: mvn test --file pom.xml
