name: Selenium Cucumber Tests
on: workflow_dispatch
jobs:
  run-tests:
    build:
      strategy:
        matrix:
          browser: [chrome,edge]
    runs-on: [self-hosted, adem-macos]
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Compile Maven Project
        run: mvn compile
      - name: Run Selenium Cucumber Tests
        id: run-tests
        run: mvn test -Dbrowser=${{ matrix.browser }}
      - name: Upload Target Folder
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: ${{ github.workspace }}/target
      - name: Test Report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ${{ github.workspace }}/target/surefire-reports/TEST-cucumberOptions.TestNGTestRunner.xml
          reporter: java-junit
          #java-version: 11


