name: Selenium Cucumber Tests

on: [push]

env:
  CHROME_BIN: /usr/bin/google-chrome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          sudo apt-get install -y maven

      - name: Run tests
        run: |
          mvn test \
          -Dwebdriver.chrome.driver=/usr/lib/chromium-browser/chromedriver \
          -Dwebdriver.chrome.bin=$CHROME_BIN \
          -Dcucumber.options="--tags @wip"

