name: Selenium Cucumber Tests
on: workflow_dispatch
jobs:
  run-tests:
    runs-on: [self-hosted, adem-macos]
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: framework-deps-${{ hashFiles('**/pom.xml') }}
      - name: Run Selenium Cucumber Tests
        run: mvn clean test
      - name: Upload Target Folder
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: ${{ github.workspace }}/target
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: ${{ github.workspace }}/target/surefire-reports/TEST-cucumberOptions.TestNGTestRunner.xml
          reporter: java-junit
          #java-version: 11


